<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>simple-csharp-greeter</AssemblyName>
    <Description>Minimal simple C# add-on for Fabulor.</Description>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\src\managed\Fabulor.PluginAbstractions\Fabulor.PluginAbstractions.csproj">
      <Private>false</Private>
    </ProjectReference>
  </ItemGroup>

</Project>
