<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>true</UseWindowsForms>
    <AssemblyName>Fabulor.BA</AssemblyName>
    <RootNamespace>Fabulor.Setup</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <ApplicationIcon>..\..\data\icons\fabulor.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="WixToolset.BootstrapperApplicationApi" Version="7.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="..\..\data\icons\fabulor.ico" Link="Assets\fabulor.ico" />
    <Resource Include="..\..\data\icons\Fabulor.svg" Link="Assets\Fabulor.svg" />
    <Resource Include="..\Licence.rtf" Link="Assets\Licence.rtf" />
  </ItemGroup>

</Project>
