icondir = join_paths(get_option('datadir'), 'icons/hicolor')
install_data(
  'fabulor.png',
  rename: 'net.fabulor.Fabulor.png',
  install_dir: join_paths(icondir, '48x48/apps')
)
install_data(
  'Fabulor.svg',
  rename: 'net.fabulor.Fabulor.svg',
  install_dir: join_paths(icondir, 'scalable/apps')
)
